config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users
  resources :attendances, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"

    validates_uniqueness_of :attendee_id, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :attendances

  scope :past, -> { where("date < ?", DateTime.current) }
  scope :upcoming, -> { where("date >= ?", DateTime.current) }

 # queries through class methods

 # def self.past
 #   Event.where("date < ?", DateTime.current)
 # end

 # def self.upcoming
 #   Event.where("date >= ?", DateTime.current)
 # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: "creator_id"
  has_many :attendances, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    before_action :is_logged_in?

    def create
        event = Event.find(params[:event_id])
        @attendance = current_user.attendances.build(attended_event_id: event.id)
        if @attendance.save
            flash[:notice] = "You are attending #{event.name}"
            redirect_to current_user
        else
            flash[:alert] = "You are already attending #{event.name}"
            redirect_to event_path(params[:event_id])
        end
    end

    def destroy
        user_id = params[:attendee_id]
        event = Event.find(params[:attended_event_id])

        @attendance = Attendance.find_by(attendee_id: user_id, attended_event_id: event.id)
        if @attendance.destroy
            flash[:notice] = "You are no longer attending #{event.name}"
            redirect_to event_path(event.id)
        else
            flash[:alert] = "Failed to stop attending #{event.name}"
            render root_path
        end

    end
    
    private

    def is_logged_in?
        unless user_signed_in?
            redirect_to new_user_session_path
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = current_user.events.build
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        if @event.update
            redirect_to event_path
        else
            flash[:alert] = "failed to update #{@event.name}"
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        if @event.destroy
            flash[:notice] = "#{@event.name} has been deleted"
            redirect_to root_path
        else
            flash[:alert] = "Failed to delete event: #{@event.name}"
            render :show
        end
    end

    private
    def event_params
        params.require(:event).permit(:name, :location, :date)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>

<h3>Past Events</h3>
<% Event.past.each do |event| %>
    <%= link_to event.name, event %><br />
<% end %>

<h3>Upcoming Events</h3>
<% Event.upcoming.each do |event| %>
    <%= link_to event.name, event %><br />
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
    <%= form.text_field :name %>
    <%= form.text_field :location %>
    <%= form.datetime_select :date %>

    <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<div>
    <% if user_signed_in? and current_user.id == @event.creator.id %>
        <%= button_to "Edit", edit_event_path, method: :get%>
        <%= button_to "Delete", event_path, method: :delete%>
    <% end %>
</div>
<div>
    <h1 text-align = "center"><%= @event.name %></h2>
    <%= @event.location %><br />
    <%= @event.date.strftime("%b %d %Y, %l:%M %P")%>
    <div>Hosted by <%= link_to @event.creator.name, @event.creator%></div>
    <% if @event.date < DateTime.current %>
        <%= button_to "This event has passed", {}, :disabled => true %>
        
    <% else %>
        <% if user_signed_in? and current_user.attended_events.where("attended_event_id = ?", @event.id).count > 0%>
            <%= button_to "Attending", attendance_path, method: :delete, params: {:attendee_id => current_user.id, :attended_event_id => @event.id} %>
        <% else %>
            <%= button_to "Attend this event", attendances_path, params: {:event_id => @event.id}%>
        <% end %>
    <% end %>
</div>
<div>
    <div>List of Attendees</div>
    <% @event.attendees.each do |attendee| %>
        <%= attendee.name %><br />
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class = "container">
    <nav>
        <ul><%= button_to "Home", root_path, method: :get%></ul>
        <ul><%= button_to "Sign Up", new_user_registration_path, method: :get%></ul>
        <% if user_signed_in? %>
            <ul><%= button_to "Sign Out", destroy_user_session_path, method: :delete%></ul>
            <ul><%= button_to "Create Event", new_event_path, method: :get%></ul>
        <% else %>
            <ul><%= button_to "Sign In", new_user_session_path, method: :get%></ul>
        <% end %>
    </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/users/show.html.erb
<div>
    <h1><%= @user.name %>'s Events</h1>
    <% @user.events.each do |event|%>
        <p> <%= event.name%> </p></ br>
    <% end %>
</div>

<div>
    <h3>Past Events Attended</h3>
    <% @user.attended_events.where("date < ?", DateTime.current).each do |event|%>
        <%= link_to event.name, event%>
    <% end %>
</div>

<div>
    <h3>Upcoming Events</h3>
    <% @user.attended_events.where("date >= ?", DateTime.current).each do |event|%>
        <%= link_to event.name, event%>
    <% end %>
</div>